import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar/navbar";
import Session from "@/context/session-provider";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import CartProvider from "@/context/cart-provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session>
          <CartProvider>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-grow">{children}</main>
              <Toaster />
              <Footer />
            </div>
          </CartProvider>
        </Session>
      </body>
    </html>
  );
}
